name: failure
on:
  workflow_dispatch:
    inputs:
      combined_string:
        description: 'Enter a string to split'
        required: true

jobs:
  split-string:
    runs-on: ubuntu-latest
    steps:
      - name: Split the string
        run: |
          INPUT_STRING="${{ github.event.inputs.combined_string }}"
          IFS='#' read -r zip_name rom_url <<< "$INPUT_STRING"
          echo "ZIP_NAME=$zip_name" >> $GITHUB_ENV
          echo "ROM_URL=$rom_url" >> $GITHUB_ENV

      - name: 安装依赖
        run: |
          sudo apt-get update
          
          sudo apt install aria2 liblzma-dev brotli lz4
          
          
          BUILD_TIME=$(TZ=Asia/Shanghai date +"%m%d%H%M")
          echo "BUILD_TIME=$BUILD_TIME" >> $GITHUB_ENV
      - name: 修改 hosts 文件
        run: |
          echo "47.74.196.250 bigota.d.miui.com" | sudo tee -a /etc/hosts
          echo "47.74.196.250 hugeota.d.miui.com" | sudo tee -a /etc/hosts
          sudo systemctl restart systemd-resolved
      - name: one
        run: |
          cd ${{ github.workspace }}
          echo "ROM URL: ${{ env.rom_url }}" # 正确引用环境变量
          echo ---------- 
          aria2c -s 10 -x 10 --check-certificate=false -d . -o firmware.zip "$rom_url"
          unzip firmware.zip
          chmod +x ./payload-dumper-go
          if [ -f "payload.bin" ]; then ./payload-dumper-go -p boot payload.bin; fi
          if [ -f "payload.bin" ]; then ./payload-dumper-go -p init_boot payload.bin; fi
          touch info.md
          echo "提交日期：$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')" >> info.md
          echo "直链：$rom_url" >> info.md
          if [ -f "${{ github.workspace }}/out/init_boot.img" ]; then rm ${{ github.workspace }}/out/boot.img; fi
    
      - name: two
        run: |
          cd ~
          if [ -f "${{ github.workspace }}/payload.bin" ]; then cp ${{ github.workspace }}/out/* ./; fi
          if [ -f "${{ github.workspace }}/boot.img" ]; then mv ${{ github.workspace }}/boot.img ./; fi
          mkdir done
          mv *.img done/
          cd ~
          if [ -f "${{ github.workspace }}/out/init_boot.img" ]; then
          git clone https://github.com/QingnAioo/boot.git  "$zip_name"
          mkdir -p ~/$zip_name/images
          mv ~/done/*.img ~/$zip_name/images/init_boot.img
          cd $zip_name
          rm -rf .git
          cd ~
          7z a -tzip -mx9 $zip_name.zip $zip_name/
          else
          git clone https://github.com/QingnAioo/boot.git  "$zip_name"
          mkdir -p ~/$zip_name/images
          mv ~/done/*.img ~/$zip_name/images/boot.img
          cd $zip_name
          rm -rf .git
          cd ~
          7z a -tzip -mx9 $zip_name.zip $zip_name/
          fi

      - name: three
        uses: ncipollo/release-action@v1.12.0
        with:
            artifacts: "~/$zip_name.zip"
            bodyfile: "${{ github.workspace }}/info.md"
            tag: "root1.0"
            allowUpdates: true
            token: ${{ secrets.GITHUB_TOKEN }} 
