name: fail


on:
  workflow_dispatch:
    inputs:
      rom_url:
      zip_name:
      combined_string:
        description: 'Enter a string to split'
        required: true
        
jobs:
  YIJIANROOT:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2
      - name: Split the string
        run: |
          INPUT_STRING="${{ github.event.inputs.combined_string }}"
          IFS='#' read -r ${{ github.event.inputs.zip_name }} ${{ github.event.inputs.rom_url }} <<< "$INPUT_STRING"
          echo "Part A: ${{ github.event.inputs.zip_name }}"
          echo "Part B: ${{ github.event.inputs.rom_url }}"
      - name: 安装依赖
        run: |
          sudo apt-get update
          
          sudo apt install aria2 liblzma-dev brotli lz4
          
          
          BUILD_TIME=$(TZ=Asia/Shanghai date +"%m%d%H%M")
          echo "BUILD_TIME=$BUILD_TIME" >> $GITHUB_ENV
      - name: 修改 hosts 文件
        run: |
          echo "47.74.196.250 bigota.d.miui.com" | sudo tee -a /etc/hosts
          echo "47.74.196.250 hugeota.d.miui.com" | sudo tee -a /etc/hosts
          sudo systemctl restart systemd-resolved
      - name: one
        run: |
          cd ${{ github.workspace }}
          aria2c -s 10 -x 10 --check-certificate=false -d . -o firmware.zip "${{ github.event.inputs.rom_url }}"
          unzip firmware.zip
          chmod +x ./payload-dumper-go
          if [ -f "payload.bin" ]; then ./payload-dumper-go -p boot payload.bin; fi
          if [ -f "payload.bin" ]; then ./payload-dumper-go -p init_boot payload.bin; fi
          touch info.md
          echo "提交日期：$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')" >> info.md
          echo "直链：${{ github.event.inputs.rom_url }}" >> info.md
          echo "Magisk 版本：${{ github.event.inputs.ver }}" >> info.md
          if [ -f "${{ github.workspace }}/out/init_boot.img" ]; then rm ${{ github.workspace }}/out/boot.img; fi
    
      - name: two
        run: |
          cd ~
          if [ -f "${{ github.workspace }}/payload.bin" ]; then cp ${{ github.workspace }}/out/* ./; fi
          if [ -f "${{ github.workspace }}/boot.img" ]; then mv ${{ github.workspace }}/boot.img ./; fi
          mkdir done
          mv *.img done/
          cd ~
          if [ -f "${{ github.workspace }}/out/init_boot.img" ]; then
          git clone https://github.com/QingnAioo/boot.git "${{ github.event.inputs.zip_name }}"
          mkdir -p ~/${{ github.event.inputs.zip_name }}/images
          mv ~/done/*.img ~/${{ github.event.inputs.zip_name }}/images/init_boot.img
          cd ${{ github.event.inputs.zip_name }}
          rm -rf .git
          cd ~
          7z a -tzip -mx9 ${{ github.event.inputs.zip_name }}.zip ${{ github.event.inputs.zip_name }}/
          else
          git clone https://github.com/QingnAioo/boot.git "${{ github.event.inputs.zip_name }}"
          mkdir -p ~/${{ github.event.inputs.zip_name }}/images
          mv ~/done/*.img ~/${{ github.event.inputs.zip_name }}/images/boot.img
          cd ${{ github.event.inputs.zip_name }}
          rm -rf .git
          cd ~
          7z a -tzip -mx9 ${{ github.event.inputs.zip_name }}.zip ${{ github.event.inputs.zip_name }}/
          fi

      - name: three
        uses: ncipollo/release-action@v1.12.0
        with:
            artifacts: "~/${{ github.event.inputs.zip_name }}.zip"
            bodyfile: "${{ github.workspace }}/info.md"
            tag: "root1.0"
            allowUpdates: true
            token: ${{ secrets.GITHUB_TOKEN }}
