name: Split String Example
on:
  workflow_dispatch:
    inputs:
      combined_string:
        description: 'Enter a string to split'
        required: true

jobs:
  split-string:
    runs-on: ubuntu-latest
    steps:
      - name: Split the string
        run: |
         wget -qO - https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/microsoft.gpg
         sudo apt-get clean
         sudo apt-get update
