name: Split String Example
on:
  workflow_dispatch:
    inputs:
      combined_string:
        description: 'Enter a string to split'
        required: true

jobs:
  split-string:
    runs-on: ubuntu-latest
    steps:
      - name: Split the string
        run: |
         sudo apt-get clean
         sudo apt-get update
